from enum import Enum


class ServiceOrderStatus(str, Enum):
    RECEIVED = "RECEIVED"
    DIAGNOSIS = "DIAGNOSIS"
    WAITING_APPROVAL = "WAITING_APPROVAL"
    IN_PROGRESS = "IN_PROGRESS"
    FINISHED = "FINISHED"
    DELIVERED = "DELIVERED"
